const nationalities = [
   "Afghan",
   "Albanian",
   "Algerian",
   "American",
   "Andorran",
   "Angolan",
   "Antiguans",
   "Argentinean",
   "Armenian",
   "Australian",
   "Austrian",
   "Azerbaijani",
   "Bahamian",
   "Bahraini",
   "Bangladeshi",
   "Barbadian",
   "Barbudans",
   "Batswana",
   "Belarusian",
   "Belgian",
   "Belizean",
   "Beninese",
   "Bhutanese",
   "Bolivian",
   "Bosnian",
   "Brazilian",
   "British",
   "Bruneian",
   "Bulgarian",
   "Burkinabe",
   "Burmese",
   "Burundian",
   "Cambodian",
   "Cameroonian",
   "Canadian",
   "Cape Verdean",
   "Central African",
   "Chadian",
   "Chilean",
   "Chinese",
   "Colombian",
   "Comoran",
   "Congolese",
   "Costa Rican",
   "Croatian",
   "Cuban",
   "Cypriot",
   "Czech",
   "Danish",
   "Djibouti",
   "Dominican",
   "Dutch",
   "East Timorese",
   "Ecuadorean",
   "Egyptian",
   "Emirian",
   "Equatorial Guinean",
   "Eritrean",
   "Estonian",
   "Ethiopian",
   "Fijian",
   "Filipino",
   "Finnish",
   "French",
   "Gabonese",
   "Gambian",
   "Georgian",
   "German",
   "Ghanaian",
   "Greek",
   "Grenadian",
   "Guatemalan",
   "Guinea-Bissauan",
   "Guinean",
   "Guyanese",
   "Haitian",
   "Herzegovinian",
   "Honduran",
   "Hungarian",
   "I-Kiribati",
   "Icelander",
   "Indian",
   "Indonesian",
   "Iranian",
   "Iraqi",
   "Irish",
   "Israeli",
   "Italian",
   "Ivorian",
   "Jamaican",
   "Japanese",
   "Jordanian",
   "Kazakhstani",
   "Kenyan",
   "Kittian and Nevisian",
   "Kuwaiti",
   "Kyrgyz",
   "Laotian",
   "Latvian",
   "Lebanese",
   "Liberian",
   "Libyan",
   "Liechtensteiner",
   "Lithuanian",
   "Luxembourger",
   "Macedonian",
   "Malagasy",
   "Malawian",
   "Malaysian",
   "Maldivan",
   "Malian",
   "Maltese",
   "Marshallese",
   "Mauritanian",
   "Mauritian",
   "Mexican",
   "Micronesian",
   "Moldovan",
   "Monacan",
   "Mongolian",
   "Moroccan",
   "Mosotho",
   "Motswana",
   "Mozambican",
   "Namibian",
   "Nauruan",
   "Nepalese",
   "New Zealander",
   "Nicaraguan",
   "Nigerian",
   "Nigerien",
   "North Korean",
   "Northern Irish",
   "Norwegian",
   "Omani",
   "Pakistani",
   "Palauan",
   "Panamanian",
   "Papua New Guinean",
   "Paraguayan",
   "Peruvian",
   "Polish",
   "Portuguese",
   "Qatari",
   "Romanian",
   "Russian",
   "Rwandan",
   "Saint Lucian",
   "Salvadoran",
   "Samoan",
   "San Marinese",
   "Sao Tomean",
   "Saudi",
   "Scottish",
   "Senegalese",
   "Serbian",
   "Seychellois",
   "Sierra Leonean",
   "Singaporean",
   "Slovakian",
   "Slovenian",
   "Solomon Islander",
   "Somali",
   "South African",
   "South Korean",
   "Spanish",
   "Sri Lankan",
   "Sudanese",
   "Surinamer",
   "Swazi",
   "Swedish",
   "Swiss",
   "Syrian",
   "Taiwanese",
   "Tajik",
   "Tanzanian",
   "Thai",
   "Togolese",
   "Tongan",
   "Trinidadian or Tobagonian",
   "Tunisian",
   "Turkish",
   "Tuvaluan",
   "Ugandan",
   "Ukrainian",
   "Uruguayan",
   "Uzbekistani",
   "Venezuelan",
   "Vietnamese",
   "Welsh",
   "Yemenite",
   "Zambian",
   "Zimbabwean"
]

const date = new Date();
const year = date.getFullYear();
const month = (date.getMonth() + 1).toString().padStart(2,'0');
const day = date.getDate().toString().padStart(2,'0');
const dateValue = `${year}-${month}-${day}`;
const employee = {
   _id : {
      el : "input",//element tag
      label: "_id",//label of the element
      attributes : {//element attributes
         name : "_id",//currently required,see ?? improvement comment on EntityForm
         id:"user-id",
         type: "text",
         minLength: 1,
         maxLength: 30,
         disabled:true,
         readOnly:true
      }
   },
   employeeId : {
      el : "input",//element tag
      label: "Employee Id",//label of the element
      attributes : {//element attributes
         name : "employeeId",//currently required,see ?? improvement comment on EntityForm
         id:"employeeId",
         type: "text",
         minLength: 1,
         maxLength: 30,
         autoFocus:true
      }
   },
   salutation : {
      el : "select",
      label: "Salutation",
      attributes : {
         name : "salutation",
         id:"salutation",
         type:"text",
         minLength: 1,
         maxLength: 5
      },
      options: [
         { value: 'Mr', text: 'Mr.'},
         { value: 'Ms', text: 'Ms.'},
         { value: 'Mrs', text: 'Mrs.'},
      ]
   },
   fname : {
      el : "input",
      label: "First Name",
      attributes : {
         name : "fname",
         id:"fname",
         type:"text",
         minLength: 1,
         maxLength: 35,
         required:true,
      }
   },
   mname : {
      el : "input",
      label: "Middle Name",
      attributes : {
         name : "mname",
         id:"mname",
         type:"text",
         minLength: 1,
         maxLength: 35,
         required:true,
      }
   },
   lname : {
      el : "input",
      label: "Last Name",
      attributes : {
         name : "lname",
         id:"lname",
         type:"text",
         minLength: 1,
         maxLength: 35,
         required:true,
      }
   },
   gender : {
      el : "select",
      label: "Gender",
      attributes : {
         name : "gender",
         id:"gender",
         minLength: 1,
         maxLength: 6,
         required:true,
      },
      options: [
         { value: 'null', text: ''},
         { value: 'male', text: 'Male'},
         { value: 'female', text: 'Female'},
      ]
   },
   nationality: {
      el : "select",
      label: "Nationality",
      attributes : {
         name : "nationality",
         id:"nationality",
         minLength: 1,
         maxLength: 15,
         defaultValue: 'Filipino',
         required:true,
      },
      options: [
         { value: 'Filipino', text: 'Filipino'},
      ]
   },
   dateOfBirth: {
      el : "input",
      label: "Date of Birth",
      attributes : {
         name : "dateOfBirth",
         id:"dateOfBirth",
         type:"date",
         minLength: 1,
         maxLength: 20,
         required:true,
      }
   },
   email: {
      el : "input",
      label: "Email",
      attributes : {
         name : "email",
         id:"email",
         type:"text",
         minLength: 1,
         maxLength: 35,
      },
   },
   alternateEmail: {
      el : "input",
      label: "Alternate Email",
      attributes : {
         name : "alternateEmail",
         id:"alternateEmail",
         type:"text",
         minLength: 1,
         maxLength: 35,
         required:true,
      },
   },
   joiningDate: {
      el : "input",
      label: "Joining Date",
      attributes : {
         name : "joiningDate",
         id:"joiningDate",
         type:"date",
         minLength: 1,
         maxLength: 35,
         required:true,
         defaultValue : dateValue
      }
   },
   jobTitle: {
      el : "input",
      label: "Job Title",
      attributes : {
         name : "jobTitle",
         id:"jobTitle",
         type:"text",
         minLength: 1,
         maxLength: 35,
      }
   },
   contactNo: {
      el : "input",
      label: "Contact No",
      attributes : {
         name : "contactNo",
         id:"contactNo",
         type:"text",
         minLength: 1,
         maxLength: 25,
         required: true,
      },
   },
   roles : {
      el: "input",
      label: "Roles",
      attributes: {
       name: "roles",
       id: "employee-roles",
       readOnly:true,
      },
      transform: r => `[ ${r.join()} ]`
     },
   createdOn: {
      el : "input",
      label: "Created On",
      attributes : {
         name : "createdOn",
         id:"createdOn",
         type:"text",
         disable:true,
         readOnly: true,
         maxLength: 45
      },
      transform : v =>String(new Date(v))
   },
   createdBy: {
      el : "input",
      label: "Created By",
      attributes : {
         name : "createdOn",
         id:"createdOn",
         type:"text",
         minLength: 1,
         maxLength: 35,
         disable:true,
         readOnly: true,
      }
   },
   modifiedOn:{
      el : "input",
      label: "Modified On",
      attributes : {
         name : "Modified On",
         id:"modifiedOn",
         type:"text",
         minLength: 1,
         maxLength: 35,
         disable:true,
         readOnly: true,
      }
   },
   modifiedBy:{
      el : "input",
      label: "Modified By",
      attributes : {
         name : "Modified By",
         id:"modifiedBy",
         type:"text",
         minLength: 1,
         maxLength: 35,
         disable:true,
         readOnly: true,
      }
   }
}

export default employee